INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (1, 'Ana Souza', 'ana.souza', '123ana', 'ADMIN', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (2, 'Carlos Lima', 'carlos.lima', 'car123', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (3, 'Fernanda Reis', 'fernanda.reis', 'fr456', 'CAIXA', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (4, 'João Pedro', 'joao.pedro', 'jp789', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (5, 'Marina Silva', 'marina.silva', 'ms159', 'ADMIN', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (6, 'Thiago Costa', 'thiago.costa', 'tc852', 'CAIXA', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (7, 'Aline Castro', 'aline.castro', 'ac963', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (8, 'Bruno Fernandes', 'bruno.fernandes', 'bf741', 'CAIXA', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (9, 'Juliana Lopes', 'juliana.lopes', 'jl258', 'VENDEDOR', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (10, 'Renato Vieira', 'renato.vieira', 'rv357', 'ADMIN', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (11, 'Camila Fernandes', 'camilafernandes', 'senha123', 'CAIXA', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (12, 'Felipe Andrade', 'felipea', '123456', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (13, 'Larissa Martins', 'larissam', 'lar123', 'ADMIN', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (14, 'Bruno Almeida', 'brunao', 'pass987', 'VENDEDOR', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (15, 'Juliana Rocha', 'julianar', 'abc123', 'CAIXA', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (16, 'Carlos Henrique', 'carlos.h', 'senha321', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (17, 'Tatiane Ribeiro', 'tatir', 'pass123', 'CAIXA', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (18, 'Eduardo Lima', 'edu.lima', '321abc', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (19, 'Letícia Alves', 'leticialves', 'le12345', 'ADMIN', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (20, 'Renato Dias', 'renatod', 'd!as789', 'VENDEDOR', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (21, 'Giovana Rocha', 'giovana.rocha', 'gr123', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (22, 'Rafael Almeida', 'rafael.almeida', 'ra456', 'CAIXA', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (23, 'Luciana Matos', 'luciana.matos', 'lm789', 'ADMIN', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (24, 'Mateus Duarte', 'mateus.duarte', 'md321', 'CAIXA', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (25, 'Patrícia Azevedo', 'patricia.azevedo', 'pa654', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (26, 'Eduardo Pires', 'eduardo.pires', 'ep987', 'ADMIN', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (27, 'Camila Mendes', 'camila.mendes', 'cm741', 'VENDEDOR', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (28, 'Henrique Sales', 'henrique.sales', 'hs852', 'CAIXA', 'S', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (29, 'Vanessa Luz', 'vanessa.luz', 'vl963', 'VENDEDOR', 'N', '2025-04-01');

INSERT INTO TBL_USUARIOS (ID_USUARIO, NOME, LOGIN, SENHA, PERFIL, ATIVO, DATA_CRIACAO)
VALUES (30, 'Rodrigo Campos', 'rodrigo.campos', 'rc159', 'ADMIN', 'S', '2025-04-01');
