--INNER JOIN--
SELECT v.ID_VENDA, c.NOME AS CLIENTE, v.VALOR_TOTAL, v.FORMA_PAGAMENTO
FROM TBL_VENDAS v
INNER JOIN TBL_CLIENTES c ON v.ID_CLIENTE = c.ID_CLIENTE;

--LEFT JOIN--
SELECT c.ID_CLIENTE, c.NOME, v.ID_VENDA, v.VALOR_TOTAL
FROM TBL_CLIENTES c
LEFT JOIN TBL_VENDAS v ON c.ID_CLIENTE = v.ID_CLIENTE;

--RIGHT JOIN--
SELECT c.ID_CLIENTE, c.NOME, v.ID_VENDA, v.VALOR_TOTAL
FROM TBL_CLIENTES c
RIGHT JOIN TBL_VENDAS v ON c.ID_CLIENTE = v.ID_CLIENTE;

--FULL JOIN--
SELECT c.ID_CLIENTE, c.NOME, v.ID_VENDA, v.VALOR_TOTAL
FROM TBL_CLIENTES c
FULL JOIN TBL_VENDAS v ON c.ID_CLIENTE = v.ID_CLIENTE;