-- Domínio para controle de ativo/inativo
CREATE DOMAIN DM_ATIVO AS CHAR(1)
CHECK (VALUE IN ('S', 'N'));

-- Domínio para datas de criação/cadastro
CREATE DOMAIN DM_DATA_CRIACAO AS DATE;

-- Tabela de Produtos
CREATE TABLE TBL_PRODUTOS (
    ID_PRODUTO INTEGER NOT NULL,
    CODIGO VARCHAR(20),
    DESCRICAO VARCHAR(100),
    PRECO_CUSTO DECIMAL(10,2),
    PRECO_VENDA DECIMAL(10,2),
    CATEGORIA VARCHAR(50),
    QUANTIDADE_ESTOQUE INTEGER,
    FORNECEDOR VARCHAR(100),
    ATIVO DM_ATIVO,
    DATA_CADASTRO DM_DATA_CRIACAO,
    PRIMARY KEY (ID_PRODUTO)
);

-- Tabela de Clientes
CREATE TABLE TBL_CLIENTES (
    ID_CLIENTE INTEGER NOT NULL,
    NOME VARCHAR(100),
    CPF_CNPJ VARCHAR(20),
    ENDERECO VARCHAR(150),
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    DATA_NASCIMENTO DATE,
    HISTORICO_COMPRAS VARCHAR(255),
    PREFERENCIAS VARCHAR(255),
    ATIVO DM_ATIVO,
    PRIMARY KEY (ID_CLIENTE)
);

-- Tabela de Vendas
CREATE TABLE TBL_VENDAS (
    ID_VENDA INTEGER NOT NULL,
    DATA_VENDA DM_DATA_CRIACAO,
    HORA TIME,
    ID_CLIENTE INTEGER,
    ID_VENDEDOR INTEGER,
    VALOR_TOTAL DECIMAL(10,2),
    DESCONTO DECIMAL(10,2),
    FORMA_PAGAMENTO VARCHAR(50),
    PRIMARY KEY (ID_VENDA)
);

-- Tabela de Usuários
CREATE TABLE TBL_USUARIOS (
    ID_USUARIO INTEGER NOT NULL,
    NOME VARCHAR(100),
    LOGIN VARCHAR(50),
    SENHA VARCHAR(50),
    PERFIL VARCHAR(30),
    ATIVO DM_ATIVO,
    DATA_CRIACAO DM_DATA_CRIACAO,
    PRIMARY KEY (ID_USUARIO)
);

--Criação das tabelas com PKComposta

CREATE TABLE TBL_ITENS_VENDA (
    ID_VENDA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER,
    PRECO_UNITARIO DECIMAL(10,2),
    DESCONTO DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    PRIMARY KEY (ID_VENDA, ID_PRODUTO)
);

CREATE TABLE TBL_COMISSOES (
    ID_VENDEDOR INTEGER NOT NULL,
    ID_VENDA INTEGER NOT NULL,
    VALOR_COMISSAO DECIMAL(10,2),
    DATA_COMISSAO DM_DATA_CRIACAO,
    PRIMARY KEY (ID_VENDEDOR, ID_VENDA)
);

-- FKs da tabela TBL_VENDAS
ALTER TABLE TBL_VENDAS
ADD CONSTRAINT FK_VENDAS_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTES(ID_CLIENTE);

ALTER TABLE TBL_VENDAS
ADD CONSTRAINT FK_VENDAS_USUARIO
FOREIGN KEY (ID_VENDEDOR) REFERENCES TBL_USUARIOS(ID_USUARIO);

-- FKs da tabela TBL_ITENS_VENDA
ALTER TABLE TBL_ITENS_VENDA
ADD CONSTRAINT FK_ITENS_VENDA_VENDA
FOREIGN KEY (ID_VENDA) REFERENCES TBL_VENDAS(ID_VENDA);

ALTER TABLE TBL_ITENS_VENDA
ADD CONSTRAINT FK_ITENS_VENDA_PRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TBL_PRODUTOS(ID_PRODUTO);

-- FKs da tabela TBL_COMISSOES
ALTER TABLE TBL_COMISSOES
ADD CONSTRAINT FK_COMISSOES_VENDA
FOREIGN KEY (ID_VENDA) REFERENCES TBL_VENDAS(ID_VENDA);

ALTER TABLE TBL_COMISSOES
ADD CONSTRAINT FK_COMISSOES_USUARIO
FOREIGN KEY (ID_VENDEDOR) REFERENCES TBL_USUARIOS(ID_USUARIO);